# Generated by Django 4.1.5 on 2023-03-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("date_joined",),
                "verbose_name": "User",
                "verbose_name_plural": "User",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                default="default.jpg", upload_to="avatar", verbose_name="avatar"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="email",
                max_length=255,
                null=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "unknown"), (0, "man"), (0, "female")],
                default=0,
                help_text="gender",
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="username",
                max_length=150,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
