# Generated by Django 4.1.5 on 2023-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_alter_user_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                default="avatar/default.jpg", upload_to="avatar", verbose_name="avatar"
            ),
        ),
    ]
