# Generated by Django 4.1.5 on 2023-03-16 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelete", models.BooleanField(default=False)),
                ("book_type", models.CharField(max_length=20, verbose_name="type")),
            ],
            options={"verbose_name": "book type", "verbose_name_plural": "book type",},
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelete", models.BooleanField(default=False)),
                (
                    "book_name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="book name"
                    ),
                ),
                (
                    "book_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="books/image/%Y/%m",
                        verbose_name="image",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="price"
                    ),
                ),
                (
                    "brief_introduction",
                    models.CharField(max_length=200, verbose_name="brief introduction"),
                ),
                (
                    "b_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.booktype",
                        verbose_name="type",
                    ),
                ),
            ],
            options={"verbose_name": "book", "verbose_name_plural": "book",},
        ),
        migrations.CreateModel(
            name="BookReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelete", models.BooleanField(default=False)),
                ("b_name", models.CharField(max_length=20, verbose_name="商品名称")),
                ("username", models.CharField(max_length=20, verbose_name="买家昵称")),
                (
                    "avatar",
                    models.CharField(default=None, max_length=200, verbose_name="买家头像"),
                ),
                (
                    "date_publish",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="发表时间"
                    ),
                ),
                (
                    "b_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.books",
                        verbose_name="book",
                    ),
                ),
            ],
            options={
                "verbose_name": "book review",
                "verbose_name_plural": "book review",
            },
        ),
    ]
